#!/bin/bash

echo -e "\033[01;34mHistory from \033[01;33m.bash_history\033[00m"
cat -n "$HOME/.bash_history"

pushd $HOME >/dev/null
for F in `find . -maxdepth 1 -name ".bash_history_hiset_*"`; do
    CUT_FILE=${F#${F:0:22}}
    echo -e "\033[01;34mHistory from \033[01;33m${CUT_FILE}\033[00m"
    cat -n $F
done
popd >/dev/null